# Generated by Django 5.1.2 on 2024-10-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('descricao', models.TextField()),
                ('instituicao', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=50)),
            ],
        ),
    ]
