# Generated by Django 5.1.2 on 2024-10-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_estagio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
    ]
